# Generated by Django 5.1.1 on 2024-12-27 11:12

import django.db.models.deletion
import todoapp.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", todoapp.manager.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="tasks",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
