# Generated by Django 5.1.1 on 2024-12-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0002_alter_user_managers_alter_tasks_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
