# Generated by Django 5.1.1 on 2025-01-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0002_alter_tag_id_alter_tasks_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tag",
            name="title",
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
