# Generated by Django 5.1.1 on 2024-12-24 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("tag_id", models.AutoField(primary_key=True, serialize=False)),
                ("tag_title", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Tasks",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("dead_line", models.DateTimeField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Optional", "Optional"),
                            ("Medium", "Medium"),
                            ("Necessary", "Necessary"),
                            ("Urgent", "Urgent"),
                            ("Critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("tag", models.ManyToManyField(related_name="tasks", to="my_app.tag")),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
